apiVersion: v1
kind: Service
metadata:
  name: akka-seed
spec:
  ports:
    - port: 2551
      protocol: TCP
      targetPort: 2551
  selector:
    run: akka-seed
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    run: akka-seed
  name: akka-seed
spec:
  serviceName: akka-seed
  replicas: 2
  selector:
    matchLabels:
      run: akka-seed
  template:
    metadata:
      labels:
        run: akka-seed
    spec:
      containers:
        - name: akka-seed
          image: felipeogutierrez/explore-akka
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            #        - name: BIND_HOST_NAME
            #          valueFrom:
            #            fieldRef:
            #              apiVersion: v1
            #              fieldPath: status.podIP
            - name: SEED_NODES
              value: akka-seed-0.akka-seed,akka-seed-1.akka-seed
          command: ["/bin/sh", "-c", "HOST_NAME=${POD_NAME}.akka-seed java -jar /explore-akka.jar 39.1"]
          livenessProbe:
            tcpSocket:
              port: 2551
          ports:
            - containerPort: 2551
              protocol: TCP